# Welcome to Serverless!
#
# This file is the main config file for your service.
# It's very minimal at this point and uses default values.
# You can always add more config options for more control.
# We've included some commented out config examples here.
# Just uncomment any of them to get that config option.
#
# For full config options, check the docs:
#    docs.serverless.com
#
# Happy Coding!

service: sizeless

provider:
  name: aws
  runtime: nodejs8.10
  memorySize: 256
  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:GetObject
        - s3:PutObject
      Resource:
        - 'arn:aws:s3:::*'

functions:
  sizeless:
    handler: handler.sizeless
    environment:
      bucket: rodrigo-sizeless-tests
      pictureQualityLevel: 50
    events:
      - s3:
          bucket: rodrigo-sizeless-tests
          event: s3:ObjectCreated:*
          rules:
            # You may create a subfolder to allocate your uploads.
            # - prefix: pictures/
            - suffix: .jpg
      - s3:
          bucket: rodrigo-sizeless-tests
          event: s3:ObjectCreated:*
          rules:
            - suffix: .png
